Traceback (most recent call last):
  File "/Users/shafu/Library/Python/3.8/lib/python/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/shafu/Library/Python/3.8/lib/python/site-packages/nbclient/client.py", line 1253, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/shafu/Library/Python/3.8/lib/python/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/shafu/Library/Python/3.8/lib/python/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/shafu/Library/Python/3.8/lib/python/site-packages/nbclient/client.py", line 693, in async_execute
    await self.async_execute_cell(
  File "/Users/shafu/Library/Python/3.8/lib/python/site-packages/nbclient/client.py", line 1010, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/shafu/Library/Python/3.8/lib/python/site-packages/nbclient/client.py", line 904, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print(stack.pop())
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/08/q0syv9y576b_rnls32m9d3nr0000gn/T/ipykernel_13808/1192403925.py[0m in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0;31m [0mprint[0m[0;34m([0m[0mstack[0m[0;34m.[0m[0mpop[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mTypeError[0m: pop() missing 1 required positional argument: 'n'
TypeError: pop() missing 1 required positional argument: 'n'

